version: '3.1'
services:
  client:
    build:
      context: ./BotManClient
      dockerfile: Dockerfile
    depends_on:
      - "server"
  server:
    build:
      context: ./BotManServer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
